## <u>NumPy</u>
designed for fast numerical computing

In [46]:
import numpy as np
import time

In [47]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>



### Python List vs NumPy Arrays

1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks
3. Uses less memory (optimized storage)
4. Built-in mathemetical functions
5. Supports dicrect vectorized operation

In [48]:
# Execution performance
size = 100_000_000

# Python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

# NumPy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seconds")

python list time = 16.771239042282104 seconds
numpy array time = 0.21596574783325195 seconds


In [49]:
# Memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


### So why is NumPy faster?
- Homogeneous Data Types and Contiguous Memory
- Vector Operations & C Implementations 
- Redued Overhead

### Creating NumPy Arrays

In [50]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U21


In [51]:
# Create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> (6,)


In [52]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [53]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D)
print(arr2D.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [54]:
# Create
arr1 = np.zeros((2, 3)) # prefill
print(arr1)
print(arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [55]:
# Create
arr1 = np.zeros((2, 3), dtype="int64") # prefill
print(arr1)
print(arr1.shape)

arr2 = np.ones((2, 3)) # prefill
print(arr2, arr2.shape)

[[0 0 0]
 [0 0 0]]
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)


In [56]:
arr3 = np.ones((5, )) # prefill
print(arr3, arr3.shape)

[1. 1. 1. 1. 1.] (5,)


In [57]:
arr4 = np.full((3, 4), 100) #prefill with val
print(arr4, arr4.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [58]:
arr5 = np.eye((4)) #Identity matrix
print(arr5, arr5.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


In [59]:
arr6 = np.arange(1, 11)
print(arr6, arr6.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [60]:
arr7 = np.arange(1, 11, 2)
print(arr7, arr7.shape)

[1 3 5 7 9] (5,)


In [61]:
arr8 = np.arange(0, 11, 2)
print(arr8, arr8.shape)

[ 0  2  4  6  8 10] (6,)


In [62]:
arr6 = np.arange(1, 11, 2)
print(arr6, arr6.shape)

[1 3 5 7 9] (5,)


In [63]:
# Creating NumPy Arrays - from scratch
arr1 = np.zeros((3, 4)) #pre-filled with 0's
print(arr1, arr1.shape)

arr2 = np.ones((3, 3)) #pre-filled with 1's
print(arr2, arr2.shape)

arr3 = np.full((2, 3), 5) #pre-filled with a num
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4)

arr5 = np.arange(1, 20, 2) #elements in range
print(arr5)

arr6 = np.linspace(0, 10, 5) #evenly spaced array
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.   2.5  5.   7.5 10. ]


### Properties

In [64]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) #dimensions = m x n
print(arr.size) #tot els - 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


### Operations on NumPy Arrays
- Reshaping
- Indexing (1D & 2D array)
- Fancy & Boolean Indexing
- Slicing

In [65]:
# Operations on arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattend = arr.flatten() # 2D => 1D
print(flattend, flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [66]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[3])

1
4


In [67]:
# Indexing
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1][1])

5


In [68]:
# Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [69]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [70]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]


In [71]:
# Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [72]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


## Common Data Type
- Integers: int32, int64
- Floating point nums: float32, float64
- Bloolean: bool
- Complex nums: complex64, complex128
- String: S (byte-str) & U (unicode-str)
- Object: generic python objects - object

In [73]:
# Data Type

arr = np.array([1, 2, 3, 4, 5])

print(arr, arr.dtype)

[1 2 3 4 5] int64


In [74]:
# Data Type

arr = np.array([1, 2, 3.14, 4, 5])

print(arr, arr.dtype)

[1.   2.   3.14 4.   5.  ] float64


In [75]:
# Data Type

arr = np.array([1, 2, 3, 4, 5, "Prime"])

print(arr, arr.dtype)

['1' '2' '3' '4' '5' 'Prime'] <U21


In [76]:
# How Complex numbers work

arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])

print(arr1 + arr2)
print(arr1 - arr2)

[5.+8.j]
[1.+2.j]


In [77]:
# Object

arr = np.array(["Prime", {1, 2, 3}, 3.14])

print(arr, arr.dtype)

['Prime' {1, 2, 3} 3.14] object


## Axes in Multi-dimensional arrays

In [78]:
# Multi - dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_row = np.sum(arr2D, axis = 1)
print(sum_of_row)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [79]:
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])  # 2 x 3 x 2
print(arr3D)

#indexing
print(arr3D[0, 1, 1])
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, 0, :])  # first row from both leyers
print(arr3D[:, :, 0])  # first row from both leyers

arr3D[:, 0, :] = 99  # first row from both leyers
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


## Vectorization & Broadcasting

In [80]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])

print(arr ** 2)

[ 1  4  9 16 25]


In [81]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])

print(arr + 10)

[11 12 13 14 15]


In [82]:
# Vectorization

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr + arr2)

[ 7  9 11 13 15]


In [83]:
# Broadcasting

print(arr + 5)

[ 6  7  8  9 10]


In [84]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


## Vector Normalization

In [85]:
# Normalize

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


## Important Mathematical Functions

Aggregation
- sum()
- prod()
- min()
- max()
- mean()
- std()
- var()
- median()
- argmin()
- argmax()

Power
- square()
- sqrt()
- pow(a, b)

Rounding
- round()
- floor()
- ceil()
- trunc()

Log & Exponential
- log()
- log 10()
- log2()
- exp()

EXTRAS
- unique()
- sort()
- abs()

In [86]:
# Mathematical functions

# Aggregation

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [87]:
# Power function

arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [88]:
# log

arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [89]:
# Rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1, 2, 3, 4, 5, 8, 2, 5])

print(np.unique(arr))
print(np.sort(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5 8]
[1 2 2 3 4 5 5 8]


In [90]:
arr = np.array([1, -2, -3, 4, -5, -8, 2, 5])

print(np.abs(arr))

[1 2 3 4 5 8 2 5]
